export const OrderErrorResponseMessage = {
  ORDER_WAS_NOT_FOUND: 'ORDER_WAS_NOT_FOUND',
  CANNOT_CREATE_ORDER: 'CANNOT_CREATE_ORDER',
}

export const ProductErrorResponseMessage = {
  PRODUCT_WAS_NOT_FOUND: 'PRODUCT_WAS_NOT_FOUND',
  CANNOT_CREATE_PRODUCT: 'CANNOT_CREATE_PRODUCT',
}

export const UserErrorResponseMessage = {
  USERNAME_IS_ALREADY_EXISTED: 'USERNAME_IS_ALREADY_EXISTED',
  EMAIL_IS_ALREADY_EXISTED: 'EMAIL_IS_ALREADY_EXISTED',
  USER_WAS_NOT_FOUND: 'USER_WAS_NOT_FOUND',
  CANNOT_CREATE_USER: 'CANNOT_CREATE_USER',
}

export const ErrorResponseMessage = {
  ...OrderErrorResponseMessage,
  ...ProductErrorResponseMessage,
  ...UserErrorResponseMessage,
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',
};
